DEBUG=True

# RIS Database settings
RIS_DB_HOST = ''
RIS_DB_PORT = 1521

RIS_DB_SERVICE = ''
RIS_DB_USER = ''
RIS_DB_PASSWORD = ''

# POSTGRESQL REVIEW DB settings
REVIEW_DB_NAME = 'review_app'
REVIEW_DB_USER = ''
REVIEW_DB_PASSWORD = ''
REVIEW_DB_PORT = 5432